apiVersion: v1
kind: Service
metadata:
  name: app-and-db-service
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      targetPort: 8080
      port: 8080
  selector:
    name: app-and-db-deployment

