version: "3"
services:
  db:
    image: postgres:15.1
    restart: always
    environment:
      POSTGRES_DB: db123
      POSTGRES_USER: user123
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"

  app:
    depends_on:
      - db
    restart: always
    image: country-service
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
  
  # pgAdmin:  
  #   image: dpage/pgadmin4:6.17
  #   ports:
  #     - "3000:80"

  #   environment:
  #     - PGADMIN_DEFAULT_PASSWORD=123456
  #     - PGADMIN_DEFAULT_EMAIL=si@google.com
