apiVersion: v1
kind: Pod
metadata:
  name: app-and-db
spec:
  restartPolicy: Always
  containers:
  - name: db
    image: postgres:15.1
    env:
    - name: POSTGRES_DB
      value: db123
    - name: POSTGRES_USER
      value: user123
    - name: POSTGRES_PASSWORD
      value: password123
    ports:
    - containerPort: 5432
  - name: app
    image: robersongarcia/country-service
    env:
    - name: PORT
      value: "8080"
    ports:
    - containerPort: 8080